# Generated by Django 4.2.25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0124_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileasset",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="db.issuecomment",
            ),
        ),
    ]
