# Generated by Django 4.2.30 on 2026-09-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_client_clientcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='db.client'),
        ),
    ]
