# Generated by Django 4.2.30 on 2026-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_issuetemplate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientcompany',
            name='unique_client_company_cnpj_per_workspace_when_not_deleted',
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='clientcompany',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('cnpj', ''), _negated=True)), fields=('workspace', 'cnpj'), name='unique_client_company_cnpj_per_workspace_when_not_deleted'),
        ),
    ]
